# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  theme_day: minimal
  theme_night: minimal
  font: 'minimal'
  font_size: M

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: false
    highlight_active_link: true

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: 'Open Problems in Single-Cell Analysis'
    description: 'Aggregating and Benchmarking Open Problems in Single Cell Analysis'
    twitter: 'dbburkhardt'
  analytics:
    google_analytics: 'UA-178400615-1'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''
site_type: Organization
local_business_type: ''
org_name: 'Open Problems in Single Cell Analysis'
description: 'Aggregating and Benchmarking Open Problems in Single Cell Analysis'
twitter: ''
# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: false
  show_search: false
  highlight_active_link: true

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
      - python
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/openproblems-bio/website'
    content_dir: content
    branch: main
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: false
