# SITE SETUP

# Appearance
appearance:
  theme_day: minimal
  theme_night: minimal
  font: 'minimal'
  font_size: M

# SEO
marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: 'Open Problems in Single-Cell Analysis'
    description: 'Aggregating and Benchmarking Open Problems in Single Cell Analysis'
    twitter: 'dbburkhardt'
  analytics:
    google_analytics: 'UA-178400615-1'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''
site_type: Organization
local_business_type: ''
org_name: 'Open Problems in Single Cell Analysis'
description: 'Aggregating and Benchmarking Open Problems in Single Cell Analysis'
twitter: ''

# Site header
header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: false
    highlight_active_link: true

# Site footer
footer:
  copyright:
    notice: '&copy; Open Problems {year} · View on [GitHub](https://github.com/openproblems-bio/openproblems)'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features
features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
    extra_languages:
      - r
      - latex
      - python
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/openproblems-bio/website'
    content_dir: content
    branch: main
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false

# Extensions
extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: false

# Security
security:
  allow_frame: true