---
title: FAQ
description: Frequently asked questions about OpenProblems and related frameworks.
---

## How can I add an external resource to my Viash component?

It is possible to add additional resources such as a file containing helper functions or other resources. All you need to do is list those files under the `functionality.resources` section of your component and refer to them in your script using `meta["resources_dir"] + "/myresource.txt"`. Please visit the Viash documentation for concrete examples on how to add [helper functions](https://viash.io/guide/component/use-helper-functions.html) and [other resources](https://viash.io/guide/component/add-resources.html) to your component.

## What does `__merge__` do?

The `__merge__` field is used to merge another YAML into a Viash config. One of its uses is in making sure that all of the components in a task has the same API.

Each task in OpenProblems contains strict definitions of the input/output file interface of its components and the file formats of those files. These interfaces are stored as YAML files in the `api` subdirectory of each task.

:::{.content-hidden}
<!-- todo: add info on nextflow tags -->
2. Nextflow ([docs](https://viash.io/guide))

You can also change the memory and CPU utilization be editing the Nextflow labels section. Available options are `[low|med|high]` for each of `mem` and `cpu`. The corresponding resource values can be found in the `/src/wf_utils/labels.config` file.
:::


:::{.content-hidden}
<!-- todo: add info on viewing the dockerfile -->
Docker ([docs](https://viash.io/guide))

**Tip #2:** You can view the dockerfile that Viash generates from the config file using the `---dockerfile` argument:
```sh
$ viash run -- ---dockerfile
```
:::