---
title: "Foundation models"
subtitle: "Modelling of single-cells to perform multiple tasks."
image: thumbnail.svg
page-layout: full
css: ../_include/task_template.css
engine: knitr
fig-cap-location: bottom
citation-location: document
bibliography:
  - library.bib
  - ../../library.bib
toc: false
---

```{r params}
#| include: false
params <- list(data_dir = "./data")
```

{{< include ../_include/_load_data.qmd >}}

{{< include ../_include/_task_description.qmd >}}

This benchmark is a work in progress.
If you are interested in evaluating foundation models for single-cell data please fill in the [form below](https://docs.google.com/forms/d/e/1FAIpQLSeB6ZHTL8yvKpA8VNRoQY28p5WDpi2WEtwRkeGSgRz3Mqw8bA/viewform?usp=sf_link) to get in touch.

<details><summary>Foundation models contact form</summary>

<iframe
  src="https://docs.google.com/forms/d/e/1FAIpQLSeB6ZHTL8yvKpA8VNRoQY28p5WDpi2WEtwRkeGSgRz3Mqw8bA/viewform?embedded=true"
  width="640"
  height="959"
  frameborder="0"
  marginheight="0"
  marginwidth="0"
>Loading…</iframe>

</details>

## Interpretation

The foundation models task combines results for multiple analysis tasks and therefore should be interpreted differently.
We treat each task as a metric that means the overall performance of a foundation model on that type of analysis.
For more information about how foundation models perform at specific aspects of each task you should refer to that tasks results page.
As well as comparing between foundation models we provide additional context by including representative standard methods for each task, allowing us to see how foundation models compare to more established methods.

The high hardware and computational requirements of some foundation models present additional challenges for benchmarking and make it difficult to obtain results in some cases.

## Summary

{{< include ../_include/_summary_figure.qmd >}}

## Results

{{< include ../_include/_results_table.qmd >}}

## Dataset info

<details><summary>Show</summary>

{{< include ../_include/_dataset_descriptions.qmd >}}

</details>

## Method info

<details><summary>Show</summary>

{{< include ../_include/_method_descriptions.qmd >}}

</details>

## Control method info

<details><summary>Show</summary>

{{< include ../_include/_baseline_descriptions.qmd >}}

</details>

## Metric info

<details><summary>Show</summary>

{{< include ../_include/_metric_descriptions.qmd >}}

</details>

<!-- ## Quality control results -->

<!-- <details><summary>Show</summary> -->

<!-- {{< include ../_include/_qc_table.qmd >}} -->

<!-- </details> -->

<!-- ## Normalisation visualisation -->

<!-- <details><summary>Show</summary> -->

<!-- {{< include ../_include/_scaling_figure.qmd >}} -->

<!-- </details> -->

## Authors

{{< include ../_include/_authors.qmd >}}
