---
title: "About the Competition"
order: 3
---

This is an official challenge in the [NeurIPS 2021 Competition Track](https://neurips.cc/Conferences/2021/CompetitionTrack). The competition is hosted by Open Problems in Single-Cell Analysis with sponsorship from [CZI](https://czi.org) and [Cellarity](https://cellarity.com). We are hosting the competition on [EvalAI](https://eval.ai/web/challenges/challenge-page/1111/overview), which is where competitors will submit code and can view a public leaderboard.

The competitions is broken down into three tracks, each with an independent set of prizes. Details about each task can be found in the [Tasks Documentation](/competitions/neurips_2021_docs/about_tasks).

The competition will run in two phases, dates can be found [here](dates.qmd):

* **Development (Sept 15 - Nov 15)** - during this development phase, participants will prototype submissions for the competition on the training data. Users will have access to starter kits with baseline methods and scripts to download code. Users can submit code to EvalAI for ranking on a public leaderboard using a subset of the public training data. These rankings are meant to help drive competition during the competition but will not be used to award prizes.
* **Testing (Nov 15 - Nov 26)** - during the testing phase, competitors will submit their final code packages for evaluation on held-out testing data. Submissions will run on our EvalAI worker, and must be formatted according to the format in the associated starter kit for each task.

Winners will receive a cash price according to the prize criteria described in each task description. [Terms and conditions](/competitions/neurips_2021_docs/submission/terms.qmd) apply.

For more information about how to get started, visit our [Getting Started](/competitions/neurips_2021_docs/about/getting_started.qmd) instructions.
