---
title: "Free compute on Saturn Cloud"
order: 40
---

To make this competition more accessible, we teamed up with [Saturn Cloud](https://saturncloud.io) to provide up to 100 hours of free compute per month to competition participants. Saturn Cloud hosts Jupyter servers that run behind the scenes on AWS. The Saturn Cloud website provides a GUI that allows you to launch cloud resources easily in your web browser.  We've created a custom image preloaded with the benchmarking dataset, several single-cell analysis tools, and exploratory notebooks.

:::{.callout-note}
Currently, the Starter Kits require Docker. Because of the way Saturn Cloud creates Jupyter Servers, Docker isn't available within the Saturn Cloud instances.

As a result, you currently cannot run the `1_unit_test.sh`, `2_generate_submission.sh`, or `3_evaluate_submission.sh` scripts on Saturn Cloud.

We are working hard to get these scripts working on Saturn Cloud, but for now, you'll need to evaluate your methods on a resource with Docker installed.
:::

### Get started

1. Go to [saturncloud.io](https://saturncloud.io) and login or create a free account
2. Under "Create a Resource" at the top of the page, click on the NeurIPS Openbio template card and click through the pop-up modals to create a new Saturn Cloud project using this template.
3. Click on the ▶ button to start a Jupyter server
4. Once the server is started, click the "Jupyter Lab" button to access the server
5. Open the data exploration notebooks in `~/project/explore/`

### Accessing the free upgrade for competitors

From the Saturn Cloud dashboard, you should see a blue circle in the lower right corner with a which chat icon inside. Click this button and send a message saying "Can you please upgrade my account for the Open Problems NeurIPS competition?"

Someone at Saturn Cloud should respond shortly and you should see 100 hours appear under the "Hours remaining" box on the left sidebar.

### Getting help with Saturn Cloud

Saturn Cloud has great documentation: [saturncloud.io/docs](https://saturncloud.io/docs/)

You can also use the chat box in the lower right corner of the Dashboard to ask for help. Saturn Cloud can help you install packages, configure your environment, and more!
