---
title: "Migration status"
engine: knitr
page-layout: full
---
 
```{r}
#| include: false
library(tidyverse)
library(kableExtra)

path <- "results_v2"
path <- "."

jsons <- list.files(path, pattern = "(method_info|metric_info).json", recursive = TRUE, full.names = TRUE)
scale <- RColorBrewer::brewer.pal(10, "RdYlGn")[c(9, 3, 2, 1)] %>%
  setNames(c("✓", "✗", "✗✗", "✗✗✗"))

df <- map_df(jsons, function(json) {
  df <- jsonlite::read_json(json, simplifyVector = TRUE)
  df$task_id <- gsub("/.*", "", df$namespace)
  if ("min" %in% names(df)) {
    df$min <- as.character(df$min)
  }
  if ("max" %in% names(df)) {
    df$max <- as.character(df$max)
  }
  as_tibble(df)
}) %>%
  mutate(
    task_id = gsub("/.*", "", namespace),
    outdated = grepl("out of date", status)
  )

# subdf <- df %>% select(task_id, id, status, v1_comp_id, config_path, v1_url, v1_commit)
```

```{r}
#| echo: false
github_op <- "https://github.com/openproblems-bio/openproblems"
github_op2 <- "https://github.com/openproblems-bio/openproblems-v2"

df %>%
  transmute(
    namespace,
    id,
    status = gsub(" \\(.*", "", status),
    v1 = glue::glue("<a href=\"{github_op}/blob/main/{v1_url}\">v1_src</a>"),
    v1_diff = glue::glue("<a href=\"{github_op}/compare/{v1_commit}...main\">v1_diff</a>"),
    v2 = glue::glue("<a href=\"{github_op2}/blob/main/src/{task_id}/{config_path}\">v2_src</a>"),
    links = glue::glue("{v1} | {v1_diff} | {v2}")
  ) %>%
  select(-v1, -v1_diff, -v2) %>%
  kbl(format = "html", escape = FALSE) %>%
  kable_styling() %>%
  column_spec(
    column = 3,
    bold = df$outdated,
    color = ifelse(df$outdated, scale[[3]], scale[[1]])
  )
```
