---
title: Website
description: Information about the OpenProblems website.
order: 30
---

### About

An overview of the project, its purpose, and objectives.

### Benchmark results

The results of the benchmarking experiments for each of the OpenProblems tasks. Each task page follows the same structure.

- **Task description**: A statement of need and the objectives of the task.

- **Summary figure**: A funkyheatmap visualisation of the performance of methods across the different datasets and metrics.

- **Results table**: A detailed view of the results obtained for each method on each dataset for each metric. Filters allow custom exploration of the results.

- **Metadata information**: Contains essential metadata about the components used in the benchmarking experiments, including datasets, methods, control methods, and metrics.

- **Quality control checks**: Helps to flag potential issues by performing various quality checks on the benchmarking results and components.

- **Raw result JSON files**: Provides access to the raw JSON files containing the complete benchmarking results for further analysis or processing.

### Events

Information about ongoing and past competitions, hackathons, courses.

### Team

The team members involved in the project and their respective roles.

### Documentation

Comprehensive documentation for OpenProblems, including information on how to download and analyse the benchmarking results, how to contribute new components, and how to create new tasks.

### Technology stack

- **GitHub Actions**: This project uses GitHub Actions for rendering and deploying the main website as well as pull request previews.

- **Quarto**: Quarto is a powerful and flexible static page generator used for rendering this website.

- **Netlify**: This website is hosted on Netlify.
