Each component has it's own set of dependencies, because different components might have conflicting dependencies.

## base images

For your convenience we have created several base images that can be used for python or R scripts. These images can be found in the OpenProblems docker repo [base_images](https://hub.docker.com/r/openproblems).
Click on the packages to view the url you need to use. You are not required to use these images but install the required packages to make sure OpenProblems works properly.

* `openproblems/base_python`
  Base image for python scripts.

* `openproblems/base_r`
  Base image for R scripts.

* `openproblems/base_pytorch_nvidia`
  Base image for scripts that use pytorch with nvidia gpu support.

* `openproblems/base_tensorflow_nvidia`
  Base image for scripts that use tensorflow with nvidia gpu support.


## custom image

Update the `setup` definition in the `platforms` section of the config file.
This section describes the packages that need to be installed in the Docker image and are required for your method to run.

If you're using a custom image use the following minimum setup:

::: {.panel-tabset}
## Python
```yaml
platforms:
  - type: docker
    Image: your custom image
    setup:
      - type: apt
        packages:
          - procps
      - type: python
        packages:
          - anndata~=0.10.0
          - scanpy~=1.10.0
          - pyyaml
          - requests
          - jsonschema
    test_setup:
      - type: python
        github: openproblems-bio/core#subdirectory=packages/python/openproblems
```

## R

```yaml
platforms:
  - type: docker
    Image: your custom image
    setup:
      - type: apt
        packages:
          - procps
          - libhdf5-dev
          - libgeos-dev
          - python3
          - python3-pip
          - python3-dev
          - python-is-python3
      - type: python
        packages:
          - rpy2
          - anndata~=0.10.0
          - scanpy~=1.10.0
          - pyyaml
          - requests
          - jsonschema
      - type: r
        packages:
          - anndata
          - BiocManager
          - reticulate
          - bit64
    test_setup:
      - type: python
        github: openproblems-bio/core#subdirectory=packages/python/openproblems
```

:::

Please check out this [guide](https://viash.io/guide/component/add-dependencies.html) for more information on how to add extra package dependencies.