```{r task_description, results="asis", echo=FALSE}
metadata <- tribble(
  ~icon, ~value,
  "bi bi-table", paste0(nrow(dataset_info), " datasets"),
  "bi bi-gear", paste0(sum(!method_info$is_baseline), " methods"),
  "bi bi-shield-check", paste0(sum(method_info$is_baseline), " control methods"),
  "bi bi-graph-up", paste0(nrow(metric_info), " metrics")
)

cat(
  paste(
    paste0("<i class=\"", metadata$icon, "\"></i> ", metadata$value),
    collapse = " · "
  )
)
```

```{r task_details, results="asis", echo=FALSE}
#| column: margin
cat("#### Info\n\n")

details <- tribble(
  ~icon, ~value,
  "bi bi-github", if (!is.null(task_info$repo)) paste0("[Repository](",task_info$repo,")") else NULL,
  "octicon--issue-opened-17", if (!is.null(task_info$issue_tracker)) paste0("[Issues](",task_info$issue_tracker,")") else NULL,
  "bi bi-tag", if (!is.null(task_info$version)) paste0(task_info$version) else NULL,
  "fa-solid fa-scale-balanced", if (!is.null(task_info$license)) paste0(task_info$license) else NULL
  ) %>% filter(!sapply(value, is.null))

cat(paste(paste0("<i class=\"", details$icon, "\"></i> ", details$value), " \n"))
```

[Task info](data/task_info.json){class="btn btn-secondary"}
[Method info](data/method_info.json){class="btn btn-secondary"}
[Metric info](data/metric_info.json){class="btn btn-secondary"}
[Dataset info](data/dataset_info.json){class="btn btn-secondary"}
[Results](data/results.json){class="btn btn-secondary"}

`r task_info$task_motivation %|% ""`

`r task_info$task_description %|% ""`
