
{{< include ../_include/_load_data.qmd >}}

```{r description, results="asis", echo=FALSE}
metadata <- tribble(
  ~icon, ~value,
  "bi bi-table", paste0(nrow(dataset_info), " datasets"),
  "bi bi-gear", paste0(sum(!method_info$is_baseline), " methods"),
  "bi bi-shield-check", paste0(sum(method_info$is_baseline), " control methods"),
  "bi bi-graph-up", paste0(nrow(metric_info), " metrics")
)

cat(
  paste(
    paste0("<i class=\"", metadata$icon, "\"></i> ", metadata$value),
    collapse = " · "
  )
)
```

```{r details, results="asis", echo=FALSE}
#| column: margin

cat("#### Info\n\n")

details <- tribble(
  ~icon, ~value,
  "bi bi-github", paste0("[repo](",task_info$repo,")"),
  "octicon--issue-opened-17", paste0("[issues](",task_info$issue_tracker,")"),
  "bi bi-tag", paste0(task_info$version),
  "fa-solid fa-scale-balanced", paste0(task_info$license)
  )
cat(paste(paste0("<i class=\"", details$icon, "\"></i> ", details$value), " \n"))

```


[Task info](data/task_info.json){class="btn btn-secondary"}
[Method info](data/method_info.json){class="btn btn-secondary"}
[Metric info](data/metric_info.json){class="btn btn-secondary"}
[Dataset info](data/dataset_info.json){class="btn btn-secondary"}
[Results](data/results.json){class="btn btn-secondary"}


`r task_info$task_motivation %|% ""`

`r task_info$task_description %|% ""`

## Summary

{{< include ../_include/_summary_figure.qmd >}}

## Results

{{< include ../_include/_results_table.qmd >}}

## Dataset info

<details><summary>Show</summary>

{{< include ../_include/_dataset_descriptions.qmd >}}

</details>

## Method info

<details><summary>Show</summary>

{{< include ../_include/_method_descriptions.qmd >}}

</details>

## Control method info

<details><summary>Show</summary>

{{< include ../_include/_baseline_descriptions.qmd >}}

</details>

## Metric info

<details><summary>Show</summary>

{{< include ../_include/_metric_descriptions.qmd >}}

</details>

## Quality control results

<details><summary>Show</summary>

{{< include ../_include/_qc_table.qmd >}}

</details>

## Normalisation visualisation

<details><summary>Show</summary>

{{< include ../_include/_scaling_figure.qmd >}}

</details>

## Authors

```{r}
#| echo: false
if (!is.null(task_info$authors) && length(task_info$authors) > 0) {
  lines <- map_chr(task_info$authors, function(author) {
    name <- author$name
    roles <- author$roles %>% paste(collapse = ", ")
    github <- author$info$github %||% NULL
    orcid <- author$info$orcid %||% NULL

    links <- c()
    if (!is.null(github)) {
      links <- c(links, glue::glue("[{{{{< fa brands github >}}}}](https://github.com/{github})"))
    }
    if (!is.null(orcid)) {
      links <- c(links, glue::glue("[{{{{< fa brands orcid >}}}}](https://orcid.org/{orcid})"))
    }  
    links_label <- 
      if (length(links) > 0) {
        glue::glue("{paste(links, collapse = ', ')}")
      } else {
        ""
      }
    strip_margin(glue::glue("
      |* {name} ({roles}) {links_label}
      |"
    ))
  })
  knitr::asis_output(paste(lines, collapse = "\n"))
}
```

