---
title: src/datasets/
engine: knitr
---

{{< include /_include/_clone_repo.qmd >}}
{{< include /_include/_evaluate_code.qmd >}}
{{< include /_include/_read_api.qmd >}}

The dataset processing pipeline uses dataset loaders to create raw dataset files (@fig-dataset-workflow). The raw dataset files are then processed to generate common dataset files. Common dataset files are used in one or more tasks.

{{< include /documentation/_figures/_project_structure_dataset_workflow.qmd >}}

## Directory structure

- **Dataset file and component formats** (`src/datasets/api`): This folder contains specifications for dataset file formats and component interfaces. This documentation page was generated mostly by reading in these files.

- **Dataset loader** (`src/datasets/loaders`): This folder contains components to load and format datasets for various sources.

- **Dataset normalization** (`src/datasets/normalization`): This folder contains various dataset normalization methods.

- **Dataset processors** (`src/datasets/processors`): This folder contains components for processing datasets, such as computing a KNN, PCA, HVG or subsetting.

- **Resource generation scripts** (`src/common/resources_scripts`): This folder contains scripts for generating the datasets using the dataset loaders, normalization methods and processors.

- **Test resource generation scripts** (`src/common/resources_test_scripts`): This folder contains scripts for generating test resources.

```{r echo=FALSE, warning=FALSE, error=FALSE, output="asis"}
cat(render_component("src/datasets/api/comp_dataset_loader.yaml"))
cat(render_file("src/datasets/api/anndata_raw.yaml"))
cat(render_component("src/datasets/api/comp_normalization.yaml"))
cat(render_file("src/datasets/api/anndata_normalized.yaml"))
cat(render_component("src/datasets/api/comp_processor_pca.yaml"))
cat(render_component("src/datasets/api/comp_processor_hvg.yaml"))
cat(render_component("src/datasets/api/comp_processor_knn.yaml"))
cat(render_file("src/datasets/api/anndata_common_dataset.yaml"))
cat(render_component("src/datasets/api/comp_processor_subset.yaml"))
```
