---
title: Fundamentals
description: "..."
order: 10
---

To contribute new functionality to OpenProblems, please follow the steps below:

1. Search through the [GitHub Issues](https://github.com/openproblems-bio/openproblems-v2/issues)  tracker to ensure that no one else is already working on the feature you would like to add. If someone is already working on it, post in that issue to express your interest or reach out to the contributors working on the issue directly.

2. If there is no existing issue tracking the feature, create a new one.

3. [Install the necessary requirements](requirements.qmd) to work with OpenProblems.

4. Follow the [getting started](getting_started.qmd) guide to fork and clone the repository and download the necessary test resources.

6. [Run](run_tests.qmd) the provided unit tests to ensure that the new functionality passes.

7. Add an entry to the CHANGELOG.md file describing the proposed changes.

8. [Create a pull request](create_pull_request.qmd) from your branch to the OpenProblems main branch.