---
title: Your first contribution
description: How to start contributing to OpenProblems.
order: 30
engine: knitr
---

To contribute new functionality to OpenProblems, please follow the steps below:

1. Search through the [GitHub Issues](https://github.com/openproblems-bio/openproblems-v2/issues)  tracker to ensure that no one else is already working on the feature you would like to add. 
  - If someone is already working on it, post in that issue to express your interest or reach out to the contributors working on the issue directly.
  - If there is no existing issue tracking the feature, create a new one.

2. Review the [key concepts](../fundamentals/philosophy.qmd) of OpenProblems to get a good grasp of the framework as a whole.

3. Install the [necessary requirements](../fundamentals/requirements.qmd) to work with OpenProblems.

4. Follow the [getting started](../fundamentals/getting_started.qmd) guide to fork and clone the repository and download the necessary test resources.

5. Add a [method](add_a_method.qmd), [metric](add_a_metric.qmd), or [control method](add_a_control.qmd) to the framework.

6. Run the provided [unit tests](run_tests.qmd) to ensure that the new functionality passes.

7. Create a [pull request](../create_component/create_pull_request.qmd) from your branch to the OpenProblems main branch. Don't forget to add an entry to the CHANGELOG.md file describing the proposed changes.