---
title: "Spatial Decomposition"
summary: "Calling cell-type compositions for spot-based spatial transcriptomics data"
bibliography: "../../../static/bibliography/main.bib"
---

```{r}
#| include: false
params <- list(data_dir = "content/benchmarks/label_projection/data")
params <- list(data_dir = "./data")
```

{{< include ../_blocks/_setup.qmd >}}

:::{.content-hidden}
`r num_methods` methods • `r num_metrics` metrics • `r num_datasets` datasets
:::

## Description 
`r task_info$task_description %|% "Missing 'task_description'"`

## Summary

{{< include ../_blocks/_summary_figure.qmd >}}

## Scaled scores

{{< include ../_blocks/_results_table.qmd >}}

## Downloads

<a href="data/task_info.json" class="btn btn-secondary">Task info</a>
<a href="data/method_info.json" class="btn btn-secondary">Method info</a>
<a href="data/metric_info.json" class="btn btn-secondary">Metric info</a>
<a href="data/dataset_info.json" class="btn btn-secondary">Dataset info</a>
<a href="data/results.json" class="btn btn-secondary">Results</a>
<a href="data/quality_control.json" class="btn btn-secondary">Quality control</a>

## Details

{{< include ../_blocks/_descriptions.qmd >}}

{{< include ../_blocks/_qc_table.qmd >}}


<details><summary>Visualization of raw results</summary>

```{r}
#| include: false
knitr::opts_chunk$set(
  fig.width = 10,
  fig.height = nrow(method_info) * nrow(metric_info) / 4
)
```

```{r raw_results, echo=FALSE}
ggplot(results_long %>% arrange(method_id)) +
  geom_vline(aes(xintercept = x), tibble(x = c(0, 1)), linetype = "dashed", alpha = .5, colour = "red") +
  geom_path(aes(score, method_id, group = dataset_id), alpha = .25) +
  geom_point(aes(score, method_id, colour = is_baseline)) +
  facet_wrap(~metric_id, ncol = 1, scales = "free") +
  theme_bw() +
  labs(x = NULL, y = NULL)
```

</details>

