---
title: Methods
engine: knitr
---

```{r setup, include=FALSE}
library(tidyverse)
library(rlang)

strip_margin <- function(text, symbol = "\\|") {
  str_replace_all(text, paste0("(\n?)[ \t]*", symbol), "\\1") 
}

dir <- "results_v2/label_projection"
dir <- "."

task_info <- jsonlite::read_json(paste0(dir, "/data/task_info.json"))
method_info <- jsonlite::read_json(paste0(dir, "/data/method_info.json"), simplifyVector = TRUE)
```



```{r methods, echo=FALSE,warning=FALSE,error=FALSE,output="asis"}
method_info_view <- 
  method_info %>%
    arrange(type, label) %>%
    transmute(
      Name = paste0("[", label, "](https://github.com/openproblems-bio/openproblems-v2/tree/main/src/", task_info$id, "/", dirname(config_path), ")"),
      Type = type,
      Description = gsub("\n", " ", description),
      DOI = ifelse(!is.na(paper_doi), paste0("[link](https://doi.org/", paper_doi, ")"), ""),
      URL = ifelse(!is.na(code_url), paste0("[link](", code_url, ")"), "")
    )

cat(paste(knitr::kable(method_info_view, format = 'pipe'), collapse = "\n"))
```

